# Generated by Django 5.2.5 on 2026-09-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title_uk', models.CharField(max_length=160)),
                ('title_en', models.CharField(blank=True, max_length=160)),
                ('teaser_uk', models.TextField()),
                ('teaser_en', models.TextField(blank=True)),
                ('body_uk', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
                ('icon_key', models.CharField(default='truck', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['order', 'id'],
            },
        ),
    ]
