# Generated by Django 5.2.5 on 2026-09-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('from_city', models.CharField(blank=True, max_length=120)),
                ('to_city', models.CharField(blank=True, max_length=120)),
                ('cargo', models.CharField(blank=True, max_length=160)),
                ('service', models.CharField(blank=True, max_length=160)),
                ('message', models.TextField(blank=True)),
                ('consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'Новий лід'), ('progress', 'В роботі'), ('done', 'Опрацьовано')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
