# Generated by Django 5.2.15 on 2026-09-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='from_country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='to_country',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
