upstream backend_server {
    server backend:8000;
}

server {
    listen 80;
    server_name privattrans.com.ua www.privattrans.com.ua 46.101.141.186 _;

    location /healthz/ {
        proxy_pass http://backend_server;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        return 301 https://privattrans.com.ua$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name www.privattrans.com.ua;
    ssl_certificate /etc/letsencrypt/live/privattrans.com.ua/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/privattrans.com.ua/privkey.pem;
    return 301 https://privattrans.com.ua$request_uri;
}

server {
    listen 443 ssl;
    server_name privattrans.com.ua;
    ssl_certificate /etc/letsencrypt/live/privattrans.com.ua/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/privattrans.com.ua/privkey.pem;
    include /etc/nginx/proxy.conf;
}
