# Generated by Django 5.2.5 on 2026-09-23 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_proof', '0003_gallerywork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerywork',
            name='image',
            field=models.ImageField(help_text='JPG або PNG зберігається як WebP.', upload_to='gallery/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, help_text='JPG або PNG зберігається як WebP. Прозорість лишається.', upload_to='partners/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
