# Generated by Django 5.2.5 on 2026-09-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_uk', models.CharField(max_length=180)),
                ('title_en', models.CharField(blank=True, max_length=180)),
                ('description_uk', models.TextField()),
                ('description_en', models.TextField(blank=True)),
                ('h1_uk', models.CharField(blank=True, max_length=180)),
                ('h1_en', models.CharField(blank=True, max_length=180)),
            ],
            options={
                'verbose_name': 'SEO сторінки',
                'verbose_name_plural': 'SEO сторінок',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='ПРИВАТ-ТРАНС', max_length=80)),
                ('slogan_uk', models.CharField(default='Ваш надійний партнер', max_length=160)),
                ('slogan_en', models.CharField(default='your reliable partner', max_length=160)),
                ('phone', models.CharField(default='(0362) 64-24-34', max_length=40)),
                ('phone_href', models.CharField(default='+380362642434', max_length=40)),
                ('email', models.EmailField(default='privat_trans@ukr.net', max_length=254)),
                ('telegram', models.CharField(blank=True, max_length=120)),
                ('address_uk', models.CharField(default='33023, м. Рівне, вул. Відінська, 10', max_length=255)),
                ('address_en', models.CharField(default='33023, Rivne, Vidinska St. 10', max_length=255)),
                ('edrpou', models.CharField(default='35148692', max_length=20)),
                ('ipn', models.CharField(default='351486917163', max_length=20)),
                ('vat_note_uk', models.CharField(default='Платник ПДВ. Платник податку на прибуток на загальних підставах.', max_length=255)),
                ('vat_note_en', models.CharField(default='VAT payer. Corporate income tax on general terms.', max_length=255)),
                ('map_embed_url', models.URLField(blank=True)),
                ('ga4_id', models.CharField(blank=True, max_length=32)),
                ('gtm_id', models.CharField(blank=True, max_length=32)),
                ('hero_video', models.FileField(blank=True, upload_to='hero/')),
                ('hero_poster', models.ImageField(blank=True, upload_to='hero/')),
                ('default_title_uk', models.CharField(default='ПРИВАТ-ТРАНС — комплексна доставка вантажів Європа ↔️ Україна ↔️ Азія', max_length=180)),
                ('default_title_en', models.CharField(default='PRIVAT-TRANS — freight Europe ↔ Ukraine ↔ Asia', max_length=180)),
                ('default_description_uk', models.TextField(default='Повний логістичний супровід на всіх етапах роботи з вантажем. З 2007 року на ринку міжнародних перевезень.')),
                ('default_description_en', models.TextField(default='Full logistics support at every cargo stage. On the international freight market since 2007.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
    ]
