# Generated by Django 5.2.5 on 2026-09-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeroSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Hero',
                'verbose_name_plural': 'Головна — Hero',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Головна'), ('site', 'Сайт')], max_length=32)),
                ('key', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('content_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Фото'), ('url', 'Посилання'), ('video', 'Відео')], default='text', max_length=16)),
                ('text_uk', models.TextField(blank=True)),
                ('text_en', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='blocks/')),
                ('link_url', models.CharField(blank=True, max_length=512)),
                ('link_label', models.CharField(blank=True, max_length=128)),
                ('video_embed_url', models.URLField(blank=True)),
                ('video_file', models.FileField(blank=True, upload_to='blocks/video/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'CMS-блок',
                'verbose_name_plural': 'CMS-блоки',
                'ordering': ['page', 'sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('page', 'key'), name='unique_site_block_page_key')],
            },
        ),
    ]
