# Generated by Django 5.2.5 on 2026-09-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteblock_cms'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Про нас',
                'verbose_name_plural': 'Про нас',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='CalculatorPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Калькулятор',
                'verbose_name_plural': 'Калькулятор',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='ContactsPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Контакти',
                'verbose_name_plural': 'Контакти',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='FaqPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'FAQ — сторінка',
                'verbose_name_plural': 'FAQ — сторінка',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='PrivacyPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Політика конфіденційності',
                'verbose_name_plural': 'Політика конфіденційності',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='ServicesPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Послуги — сторінка',
                'verbose_name_plural': 'Послуги — сторінка',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='page',
            field=models.CharField(choices=[('home', 'Головна'), ('about', 'Про нас'), ('contacts', 'Контакти'), ('privacy', 'Політика'), ('services', 'Послуги'), ('faq', 'FAQ'), ('calculator', 'Калькулятор'), ('site', 'Сайт')], max_length=32),
        ),
    ]
