# Generated by Django 5.2.5 on 2026-09-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cms_pages_and_proxies'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeScenariosSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Три сценарії',
                'verbose_name_plural': 'Головна — Три сценарії',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
    ]
