# Generated by Django 5.2.15 on 2026-09-11 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_brand_name_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, help_text='OG-прев’ю 1200×630. Якщо порожньо — hero poster або static/media/hero-poster.jpg', upload_to='seo/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'webp', 'png'])]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_poster',
            field=models.ImageField(blank=True, help_text='Кадр-заставка (JPG/WEBP). Fallback: static/media/hero-poster.jpg', upload_to='hero/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'webp', 'png'])]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_video',
            field=models.FileField(blank=True, help_text='MP4 H.264, 12–16 с, 1080p 24/30 fps, до 10 МБ. Fallback: static/media/hero-video.mp4', upload_to='hero/', validators=[django.core.validators.FileExtensionValidator(['mp4'])]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_video_webm',
            field=models.FileField(blank=True, help_text='WebM VP9, ті самі параметри. Fallback: static/media/hero-video.webm', upload_to='hero/', validators=[django.core.validators.FileExtensionValidator(['webm'])]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='slogan_en',
            field=models.CharField(default='Your reliable partner', max_length=160),
        ),
    ]
