# Generated by Django 5.2.5 on 2026-09-23 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_seo_og_image_and_service_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteblock',
            name='image',
            field=models.ImageField(blank=True, help_text='JPG або PNG зберігається як WebP.', upload_to='blocks/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_poster',
            field=models.ImageField(blank=True, help_text='JPG або PNG зберігається як WebP. Fallback: static/media/hero-poster.jpg', upload_to='hero/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, help_text='OG-прев’ю 1200×630. JPG або PNG зберігається як WebP. Якщо порожньо — hero poster або static/media/hero-poster.jpg', upload_to='seo/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
