from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ContentSection:
    slug: str
    page_slug: str
    title: str
    blocks: tuple[tuple[str, str], ...]
    sidebar_title: str = ""
    sidebar_icon: str = "edit_note"
    preview_url: str = "/"
    description: str = ""
    visibility_key: str = ""
    admin_model_name: str = ""


CONTENT_SECTIONS: tuple[ContentSection, ...] = (
    ContentSection(
        slug="hero",
        page_slug="home",
        title="Головна — Hero",
        sidebar_title="Головна — Hero",
        sidebar_icon="image",
        preview_url="/",
        description="Тексти першого екрану головної сторінки (без TinyMCE).",
        visibility_key="hero_section_visible",
        admin_model_name="homeherosettings",
        blocks=(
            ("home", "hero_badge"),
            ("home", "hero_badge_rest"),
            ("home", "hero_title"),
            ("home", "hero_lead"),
            ("home", "hero_fact_year"),
            ("home", "hero_fact_rest"),
            ("home", "hero_form_title"),
            ("home", "hero_cta_call"),
            ("home", "hero_cta_telegram"),
            ("home", "hero_submit"),
        ),
    ),
    ContentSection(
        slug="scenarios",
        page_slug="home",
        title="Головна — Три сценарії",
        sidebar_title="Головна — Сценарії",
        sidebar_icon="view_agenda",
        preview_url="/",
        description=(
            "Блок «Три сценарії перевезення». "
            "У полях slug — slug послуги з розділу «Послуги»."
        ),
        visibility_key="scenarios_section_visible",
        admin_model_name="homescenariossettings",
        blocks=(
            ("home", "scenarios_eyebrow"),
            ("home", "scenarios_title"),
            ("home", "scenarios_lead"),
            ("home", "scenarios_cta"),
            ("home", "scenario_1_title"),
            ("home", "scenario_1_text"),
            ("home", "scenario_1_slug"),
            ("home", "scenario_2_title"),
            ("home", "scenario_2_text"),
            ("home", "scenario_2_slug"),
            ("home", "scenario_3_title"),
            ("home", "scenario_3_text"),
            ("home", "scenario_3_slug"),
        ),
    ),
    ContentSection(
        slug="geography",
        page_slug="home",
        title="Головна — Географія",
        sidebar_title="Головна — Географія",
        sidebar_icon="public",
        preview_url="/#regions",
        description="Регіони Європа/Азія та міст між напрямками.",
        admin_model_name="homegeographysettings",
        blocks=(
            ("home", "regions_eyebrow"),
            ("home", "regions_title"),
            ("home", "region_eu_kicker"),
            ("home", "region_eu_title"),
            ("home", "region_eu_text"),
            ("home", "region_eu_chips"),
            ("home", "region_as_kicker"),
            ("home", "region_as_title"),
            ("home", "region_as_text"),
            ("home", "region_as_chips"),
            ("home", "corridor_eyebrow"),
            ("home", "corridor_title"),
            ("home", "corridor_lead"),
            ("home", "corridor_fact_1_value"),
            ("home", "corridor_fact_1_label"),
            ("home", "corridor_fact_2_value"),
            ("home", "corridor_fact_2_label"),
            ("home", "corridor_fact_3_value"),
            ("home", "corridor_fact_3_label"),
        ),
    ),
    ContentSection(
        slug="routes",
        page_slug="home",
        title="Головна — Маршрути",
        sidebar_title="Головна — Маршрути",
        sidebar_icon="route",
        preview_url="/#routes",
        description="Заголовки блоку маршрутів і підписи фільтра.",
        admin_model_name="homeroutessettings",
        blocks=(
            ("home", "routes_eyebrow"),
            ("home", "routes_title"),
            ("home", "routes_lead"),
            ("home", "routes_filter_all"),
            ("home", "routes_filter_europe"),
            ("home", "routes_filter_asia"),
        ),
    ),
    ContentSection(
        slug="mid",
        page_slug="home",
        title="Головна — Послуги та автопарк",
        sidebar_title="Головна — Послуги/автопарк",
        sidebar_icon="inventory_2",
        preview_url="/#services",
        description="Тизери послуг і автопарку на головній.",
        admin_model_name="homemidsettings",
        blocks=(
            ("home", "services_home_eyebrow"),
            ("home", "services_home_title"),
            ("home", "services_home_cta"),
            ("home", "fleet_home_eyebrow"),
            ("home", "fleet_home_title"),
            ("home", "fleet_home_lead"),
            ("home", "fleet_home_cta"),
            ("home", "fleet_home_fact_1_value"),
            ("home", "fleet_home_fact_1_label"),
            ("home", "fleet_home_fact_2_value"),
            ("home", "fleet_home_fact_2_label"),
            ("home", "fleet_home_fact_3_value"),
            ("home", "fleet_home_fact_3_label"),
        ),
    ),
    ContentSection(
        slug="experience",
        page_slug="home",
        title="Головна — Переваги та процес",
        sidebar_title="Головна — Переваги/процес",
        sidebar_icon="verified",
        preview_url="/#advantages",
        description="Чому з нами та кроки співпраці.",
        admin_model_name="homeexperiencesettings",
        blocks=(
            ("home", "advantages_title"),
            ("home", "advantage_1_title"),
            ("home", "advantage_1_text"),
            ("home", "advantage_2_title"),
            ("home", "advantage_2_text"),
            ("home", "advantage_3_title"),
            ("home", "advantage_3_text"),
            ("home", "advantage_4_title"),
            ("home", "advantage_4_text"),
            ("home", "advantage_5_title"),
            ("home", "advantage_5_text"),
            ("home", "process_eyebrow"),
            ("home", "process_title"),
            ("home", "process_1_title"),
            ("home", "process_1_text"),
            ("home", "process_2_title"),
            ("home", "process_2_text"),
            ("home", "process_3_title"),
            ("home", "process_3_text"),
            ("home", "process_4_title"),
            ("home", "process_4_text"),
        ),
    ),
    ContentSection(
        slug="social",
        page_slug="home",
        title="Головна — Калькулятор і соцблок",
        sidebar_title="Головна — Соцблок",
        sidebar_icon="groups",
        preview_url="/#calc-teaser",
        description="Тизер калькулятора, FAQ, відгуки, партнери, кар’єра.",
        admin_model_name="homesocialsettings",
        blocks=(
            ("home", "calc_teaser_eyebrow"),
            ("home", "calc_teaser_title"),
            ("home", "calc_teaser_item_1"),
            ("home", "calc_teaser_item_2"),
            ("home", "calc_teaser_cta"),
            ("home", "calc_teaser_panel_label"),
            ("home", "calc_teaser_route"),
            ("home", "calc_teaser_meta"),
            ("home", "calc_teaser_from"),
            ("home", "calc_teaser_to"),
            ("home", "calc_teaser_note"),
            ("home", "faq_home_title"),
            ("home", "faq_home_cta"),
            ("home", "reviews_title"),
            ("home", "partners_title"),
            ("home", "career_kicker"),
            ("home", "career_title"),
            ("home", "career_text"),
            ("home", "career_cta"),
        ),
    ),
    ContentSection(
        slug="chrome",
        page_slug="site",
        title="Сайт — CTA та форма",
        sidebar_title="Сайт — CTA / форма",
        sidebar_icon="campaign",
        preview_url="/",
        description="Глобальні CTA, лід-секція, опис у футері (не меню).",
        admin_model_name="sitechromesettings",
        blocks=(
            ("site", "footer_lead"),
            ("site", "cta_lead"),
            ("site", "cta_call"),
            ("site", "cta_telegram"),
            ("site", "lead_eyebrow"),
            ("site", "lead_title"),
            ("site", "lead_lead"),
            ("site", "lead_submit"),
            ("site", "about_resume_cta"),
        ),
    ),
    ContentSection(
        slug="page",
        page_slug="about",
        title="Про нас",
        sidebar_title="Про нас",
        sidebar_icon="info",
        preview_url="/about/",
        description="Тексти сторінки «Про нас».",
        admin_model_name="aboutpagesettings",
        blocks=(
            ("about", "about_lead"),
            ("about", "about_stat_1_value"),
            ("about", "about_stat_1_label"),
            ("about", "about_stat_2_value"),
            ("about", "about_stat_2_label"),
            ("about", "about_stat_3_value"),
            ("about", "about_stat_3_label"),
            ("about", "about_stat_4_value"),
            ("about", "about_stat_4_label"),
            ("about", "about_infra_title"),
            ("about", "about_infra_body"),
            ("about", "about_geo_title"),
            ("about", "about_geo_body"),
            ("about", "about_gallery_eyebrow"),
            ("about", "about_gallery_title"),
            ("about", "about_career_title"),
        ),
    ),
    ContentSection(
        slug="page",
        page_slug="fleet",
        title="Автопарк",
        sidebar_title="Автопарк",
        sidebar_icon="local_shipping",
        preview_url="/fleet/",
        description="Тексти сторінки автопарку.",
        admin_model_name="fleetpagesettings",
        blocks=(
            ("fleet", "fleet_lead"),
            ("fleet", "fleet_fact_1_value"),
            ("fleet", "fleet_fact_1_label"),
            ("fleet", "fleet_fact_2_value"),
            ("fleet", "fleet_fact_2_label"),
            ("fleet", "fleet_fact_3_value"),
            ("fleet", "fleet_fact_3_label"),
            ("fleet", "fleet_bodies_eyebrow"),
            ("fleet", "fleet_bodies_title"),
            ("fleet", "fleet_bodies_lead"),
            ("fleet", "fleet_body_1_title"),
            ("fleet", "fleet_body_1_text"),
            ("fleet", "fleet_body_2_title"),
            ("fleet", "fleet_body_2_text"),
            ("fleet", "fleet_body_3_title"),
            ("fleet", "fleet_body_3_text"),
            ("fleet", "fleet_capabilities_title"),
            ("fleet", "fleet_capabilities_body"),
            ("fleet", "fleet_partners_title"),
            ("fleet", "fleet_partners_body"),
            ("fleet", "fleet_faq_title"),
            ("fleet", "fleet_faq_1_q"),
            ("fleet", "fleet_faq_1_a"),
            ("fleet", "fleet_faq_2_q"),
            ("fleet", "fleet_faq_2_a"),
            ("fleet", "fleet_faq_3_q"),
            ("fleet", "fleet_faq_3_a"),
        ),
    ),
    ContentSection(
        slug="page",
        page_slug="contacts",
        title="Контакти",
        sidebar_title="Контакти",
        sidebar_icon="call",
        preview_url="/contacts/",
        description="Додатковий лід на сторінці контактів.",
        admin_model_name="contactspagesettings",
        blocks=(("contacts", "contacts_lead"),),
    ),
    ContentSection(
        slug="page",
        page_slug="privacy",
        title="Політика конфіденційності",
        sidebar_title="Політика",
        sidebar_icon="policy",
        preview_url="/privacy/",
        description="Текст політики конфіденційності.",
        admin_model_name="privacypagesettings",
        blocks=(("privacy", "privacy_body"),),
    ),
    ContentSection(
        slug="page",
        page_slug="services",
        title="Послуги — сторінка",
        sidebar_title="Послуги (сторінка)",
        sidebar_icon="view_list",
        preview_url="/services/",
        description="Лід списку послуг. Картки — у розділі «Послуги».",
        admin_model_name="servicespagesettings",
        blocks=(("services", "services_lead"),),
    ),
    ContentSection(
        slug="page",
        page_slug="faq",
        title="FAQ — сторінка",
        sidebar_title="FAQ (сторінка)",
        sidebar_icon="quiz",
        preview_url="/faq/",
        description="Лід сторінки FAQ. Питання — у розділі «FAQ».",
        admin_model_name="faqpagesettings",
        blocks=(("faq", "faq_lead"),),
    ),
    ContentSection(
        slug="page",
        page_slug="calculator",
        title="Калькулятор",
        sidebar_title="Калькулятор",
        sidebar_icon="calculate",
        preview_url="/calculator/",
        description="Тексти сторінки калькулятора (підписи полів форми — ні).",
        admin_model_name="calculatorpagesettings",
        blocks=(
            ("calculator", "calculator_lead"),
            ("calculator", "calculator_empty"),
            ("calculator", "calculator_result_label"),
            ("calculator", "calculator_disclaimer"),
            ("calculator", "calculator_submit"),
            ("calculator", "calculator_cta_lead"),
        ),
    ),
)


def get_section(page_slug: str, section_slug: str) -> ContentSection | None:
    for section in CONTENT_SECTIONS:
        if section.page_slug == page_slug and section.slug == section_slug:
            return section
    return None


def get_section_by_admin_model(admin_model_name: str) -> ContentSection | None:
    name = admin_model_name.lower()
    for section in CONTENT_SECTIONS:
        if section.admin_model_name == name:
            return section
    return None
