# Generated by Django 5.2.5 on 2026-09-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_uk', models.CharField(max_length=240)),
                ('question_en', models.CharField(blank=True, max_length=240)),
                ('answer_uk', models.TextField()),
                ('answer_en', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('show_on_home', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Питання FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order', 'id'],
            },
        ),
    ]
